
# Step 1: Login to Azure (opens browser)
#Connect-AzAccount

# Optional: set subscription explicitly (good practice)
Set-AzContext -SubscriptionId "6874b9d3-0bbe-43fd-9182-ec44214b1b4d"


$tableParams = @'
{
    "properties": {
        "schema": {
            "name": "AWSS3ServerAccessLogs_CL",
            "columns": [
                { "name": "AccessPointARN", "type": "string", "description": "ARN of the S3 access point used for the request, or '-' if not applicable." },
                { "name": "ACLRequired", "type": "string", "description": "Indicates whether an ACL was required for the request ('Yes' or '-')." },
                { "name": "AuthenticationType", "type": "string", "description": "Authentication method used (AuthHeader, QueryString, or '-' for unauthenticated)." },
                { "name": "Bucket", "type": "string", "description": "Name of the S3 bucket handling the request." },
                { "name": "BucketAccountId", "type": "string", "description": "AWS account ID that owns the bucket." },
                { "name": "BucketOwner", "type": "string", "description": "Canonical user ID of the bucket owner." },
                { "name": "BytesSent", "type": "int", "description": "Number of response bytes sent to the client, excluding HTTP overhead." },
                { "name": "CipherSuite", "type": "string", "description": "TLS cipher suite negotiated for HTTPS requests, or '-' for HTTP." },
                { "name": "ErrorCode", "type": "string", "description": "S3 error code returned in the response, or '-' if none." },
                { "name": "HostHeader", "type": "string", "description": "Endpoint (host header) used to access S3." },
                { "name": "HostId", "type": "string", "description": "Amazon S3 extended request ID (x-amz-id-2) for internal tracking." },
                { "name": "HttpStatus", "type": "int", "description": "HTTP status code returned to the client." },
                { "name": "Key", "type": "string", "description": "Object key (name/path) accessed or modified." },
                { "name": "ObjectSize", "type": "int", "description": "Size of the object in bytes." },
                { "name": "Operation", "type": "string", "description": "Type of operation executed (e.g., REST.GET.OBJECT, REST.PUT.OBJECT)." },
                { "name": "Properties", "type": "dynamic", "description": "Additional message properties and metadata." },
                { "name": "RawData", "type": "string", "description": "Original raw AWS S3 access log entry." },
                { "name": "Referer", "type": "string", "description": "HTTP Referer header indicating the source URL of the request, if present." },
                { "name": "RemoteIp", "type": "string", "description": "IP address of the requester (may be proxied or NATed)." },
                { "name": "Requester", "type": "string", "description": "Canonical user ID, IAM user, or assumed role making the request, or '-' if anonymous." },
                { "name": "RequestId", "type": "string", "description": "Unique request identifier generated by Amazon S3." },
                { "name": "RequestUri", "type": "string", "description": "Full URI path of the HTTP request." },
                { "name": "ResponseError", "type": "string", "description": "Error details returned in the response, if any." },
                { "name": "ResponseMessage", "type": "string", "description": "Response message or status description." },
                { "name": "SignatureVersion", "type": "string", "description": "Signature version used for authentication (SigV2, SigV4, or '-')." },
                { "name": "Status", "type": "string", "description": "Status of the request (success or failure indicator)." },
                { "name": "TimeGenerated", "type": "datetime", "description": "Timestamp when the S3 access log entry was generated (UTC)." },
                { "name": "TLSVersion", "type": "string", "description": "TLS version used by the client (e.g., TLSv1.2), or '-' if not applicable." },
                { "name": "TotalTime", "type": "int", "description": "Total request duration in milliseconds (from request receipt to last response byte)." },
                { "name": "TurnAroundTime", "type": "string", "description": "Time in milliseconds S3 spent processing the request (server-side processing time)." },
                { "name": "TypeName", "type": "string", "description": "Type of access request." },
                { "name": "UserAccountId", "type": "string", "description": "AWS account ID associated with the requester." },
                { "name": "UserAgent", "type": "string", "description": "Client user agent string identifying the requester application." },
                { "name": "UserARN", "type": "string", "description": "ARN of the IAM user or role making the request." },
                { "name": "UserARNAlt", "type": "string", "description": "Alternate ARN representation of the requester, if available." },
                { "name": "VersionId", "type": "string", "description": "Version ID of the object involved in the request, or '-' if not applicable." },
                { "name": "ClassName", "type": "string", "description": "Class or service classification of the event." },
                { "name": "CategoryName", "type": "string", "description": "Category classification of the event." },
                { "name": "ActivityName", "type": "string", "description": "Activity or action name associated with the event." }
            ]
        }
    }
}
'@


$restMethodParams = @{
    Path    = "/subscriptions/6874b9d3-0bbe-43fd-9182-ec44214b1b4d/resourcegroups/chitpa-sentinel-rg-01/providers/microsoft.operationalinsights/workspaces/sentinel-ws-sea-01/tables/AWSS3ServerAccessLogs_CL?api-version=2025-07-01"
    Method  = "PUT"
    Payload = $tableParams}

Invoke-AzRestMethod @restMethodParams